view: fct_orders_2026_segmented {

  sql_table_name: main.fct_orders_2026_segmented ;;

  label: "Orders 2026"
  description: "One row per order for 2026, enriched with customer order history and New, Returning or VIP segmentation."

  dimension: order_id {
    primary_key: yes
    type: string
    sql: ${TABLE}.order_id ;;
    label: "Order ID"
    description: "Unique identifier of the order."
    group_label: "Order"
    drill_fields: [order_date, customer_id, order_net_sales, qty_product, order_segmentation]
  }

  dimension: customer_id {
    type: string
    sql: ${TABLE}.customer_id ;;
    label: "Customer ID"
    description: "Unique identifier of the customer."
    group_label: "Customer"
    drill_fields: [order_id, order_date, order_segmentation]
  }

  dimension_group: order_date {
    type: time
    timeframes: [
      raw,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}.order_date ;;
    label: "Order Date"
    description: "Date on which the order was created."
    group_label: "Order"
  }

  dimension: order_segmentation {
    type: string
    sql: ${TABLE}.order_segmentation ;;
    label: "Customer Segment"
    description: "Dynamic customer segment based on the number of orders placed during the preceding 12 months. New = 0 prior orders, Returning = 1 to 3 prior orders, VIP = 4 or more prior orders."
    group_label: "Customer"
    drill_fields: [customer_id, order_id, order_date, previous_orders_12m]
  }

  dimension: previous_orders_12m {
    type: number
    sql: ${TABLE}.previous_orders_12m ;;
    label: "Previous Orders - 12 Months"
    description: "Number of orders placed by the same customer during the 12 months preceding the current order."
    group_label: "Customer"
  }

  dimension: order_net_sales {
    type: number
    sql: ${TABLE}.order_net_sales ;;
    value_format_name: "eur"
    label: "Order Revenue"
    description: "Net sales amount recorded at order level."
    group_label: "Revenue"
  }

  dimension: sales_net_sales {
    type: number
    sql: ${TABLE}.sales_net_sales ;;
    value_format_name: "eur"
    label: "Sales Revenue"
    description: "Net sales amount calculated from the associated sales lines."
    group_label: "Revenue"
  }

  dimension: qty_product {
    type: number
    sql: ${TABLE}.qty_product ;;
    label: "Products per Order"
    description: "Total quantity of products included in the order."
    group_label: "Products"
  }

  dimension: distinct_products {
    type: number
    sql: ${TABLE}.distinct_products ;;
    label: "Distinct Products"
    description: "Number of distinct products included in the order."
    group_label: "Products"
  }

  measure: count_orders {
    type: count
    label: "Orders"
    description: "Number of orders."
    group_label: "Order KPIs"
    drill_fields: [order_id, order_date, customer_id, order_segmentation]
  }

  measure: total_revenue {
    type: sum
    sql: ${order_net_sales} ;;
    value_format_name: "eur"
    label: "Total Revenue"
    description: "Total net revenue generated by orders."
    group_label: "Revenue KPIs"
    drill_fields: [order_id, order_date, customer_id, order_segmentation]
  }

  measure: average_order_value {
    type: average
    sql: ${order_net_sales} ;;
    value_format_name: "eur"
    label: "Average Order Value"
    description: "Average revenue per order."
    group_label: "Revenue KPIs"
  }

  measure: total_products {
    type: sum
    sql: ${qty_product} ;;
    label: "Total Products"
    description: "Total quantity of products sold."
    group_label: "Product KPIs"
  }

  measure: average_products_per_order {
    type: average
    sql: ${qty_product} ;;
    value_format_name: "decimal_2"
    label: "Average Products per Order"
    description: "Average number of products included in each order."
    group_label: "Product KPIs"
  }

  measure: unique_customers {
    type: count_distinct
    sql: ${customer_id} ;;
    label: "Unique Customers"
    description: "Number of distinct customers placing orders."
    group_label: "Customer KPIs"
  }

  measure: new_orders {
    type: count
    filters: [order_segmentation: "New"]
    label: "New Orders"
    description: "Number of orders classified as New."
    group_label: "Customer KPIs"
  }

  measure: returning_orders {
    type: count
    filters: [order_segmentation: "Returning"]
    label: "Returning Orders"
    description: "Number of orders classified as Returning."
    group_label: "Customer KPIs"
  }

  measure: vip_orders {
    type: count
    filters: [order_segmentation: "VIP"]
    label: "VIP Orders"
    description: "Number of orders classified as VIP."
    group_label: "Customer KPIs"
  }
}