name: 'astrafy_take_home'
version: '1.0.0'

profile: 'astrafy_take_home'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  astrafy_take_home:
    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table

vars:
  target_year: 2026
