version: 2

models:

  - name: stg_orders
    description: "Cleaned order-level data."

    columns:

      - name: order_id
        description: "Unique identifier of an order."
        tests:
          - not_null
          - unique

      - name: client_id
        description: "Identifier of the customer."
        tests:
          - not_null

      - name: order_date
        description: "Date when the order was placed."
        tests:
          - not_null


  - name: stg_sales
    description: "Cleaned sales lines at product level."

    columns:

      - name: order_id
        description: "Identifier of the order."

        tests:
          - not_null

      - name: product_id
        description: "Identifier of the product."

      - name: quantity
        description: "Quantity of products in the sales line."
